apiVersion: v1
kind: ConfigMap
data:
  elasticsearch-yml: |
    bootstrap.memory_lock: false
    cluster.name: myesdb
    discovery.zen.minimum_master_nodes: 2
    discovery.zen.ping.unicast.hosts: es-master
    http.compression: true
    network.bind_host: 0
    network.publish_host: _eth0_
    node.data: false
    node.master: true
    node.name: ${HOSTNAME}
  ES_JAVA_OPTS: -Xms512m -Xmx512m
  elasticsearch-data-yml: |
    bootstrap.memory_lock: false
    cluster.name: myesdb
    discovery.zen.minimum_master_nodes: 2
    discovery.zen.ping.unicast.hosts: es-master
    http.compression: true
    network.bind_host: 0
    network.publish_host: _eth0_
    node.data: true
    node.master: false
    node.name: ${HOSTNAME}
metadata:
  name: es
